[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "relocation-model=pic",
    "-C", "target-feature=-crt-static",
    "-C", "panic=unwind",
]

[target.aarch64-unknown-linux-musl]
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "relocation-model=pic",
    "-C", "target-feature=-crt-static",
    "-C", "panic=unwind",
]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="custom"', "-C", "link-args=-z stack-size=2097152"]